# Generated by Django 4.2.21 on 2025-05-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='alias',
            field=models.CharField(max_length=255, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='library',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code or identification'),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
