# Generated by Django 4.2.20 on 2025-05-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('project', '0004_userrole_project_userrole_role_valid'), ('project', '0005_alter_userrole_project')]

    dependencies = [
        ('project', '0003_alter_library_alias_alter_library_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['tenant_super_user', 'project_creator', 'project_admin', 'project_manager', 'instructor', 'controller', 'guest'])), name='project_userrole_role_valid'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='project.project'),
        ),
    ]
