# Generated by Django 4.2.20 on 2025-05-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_library_alias_alter_library_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['tenant_super_user', 'project_creator', 'project_admin', 'project_manager', 'instructor', 'controller', 'guest'])), name='project_userrole_role_valid'),
        ),
    ]
