# Generated by Django 4.2.20 on 2025-05-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_userrole_project_userrole_role_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='project.project'),
        ),
    ]
