# Generated by Django 4.2.21 on 2025-05-28 13:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_userrole_project_userrole_role_valid_squashed_0005_alter_userrole_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='library',
            name='is_alternate_site',
            field=models.BooleanField(default=False, verbose_name='Is alternate site'),
        ),
        migrations.AddField(
            model_name='project',
            name='active_after',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active after'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is private'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('draft', 'Draft'), ('review', 'Review'), ('active', 'Active')], default='created', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='project.library'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['created', 'draft', 'review', 'active'])), name='project_project_status_valid'),
        ),
    ]
