# Generated by Django 4.2.21 on 2025-05-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_library_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_project_status_valid',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(10, 'Created'), (20, 'Draft'), (30, 'Review'), (40, 'Active')], default=10, max_length=15, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('status__in', [10, 20, 30, 40])), name='project_project_status_valid'),
        ),
    ]
