# Generated by Django 4.2.22 on 2025-06-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_project_project_status_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(10, 'Created'), (20, 'Draft'), (30, 'Review'), (40, 'Active')], default=10, verbose_name='Status'),
        ),
    ]
