# Generated by Django 4.2.23 on 2025-06-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import epl.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0007_remove_project_project_project_status_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="settings",
            field=models.JSONField(default=dict, verbose_name="Settings"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Created"),
                    (20, "Draft"),
                    (30, "Review"),
                    (40, "Active"),
                ],
                default=10,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=25, verbose_name="Code (PPN or other)"
                    ),
                ),
                (
                    "issn",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        validators=[epl.validators.IssnValidator()],
                        verbose_name="ISSN",
                    ),
                ),
                (
                    "call_number",
                    models.CharField(blank=True, verbose_name="Call number"),
                ),
                (
                    "hold_statement",
                    models.CharField(blank=True, verbose_name="Hold statement"),
                ),
                ("missing", models.CharField(blank=True, verbose_name="Missing")),
                (
                    "publication_history",
                    models.CharField(blank=True, verbose_name="Publication history"),
                ),
                ("numbering", models.CharField(blank=True, verbose_name="Numbering")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.library",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
                "ordering": ["title"],
            },
        ),
    ]
