# Generated by Django 4.2.23 on 2025-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_project_settings_alter_project_status_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(db_index=True, max_length=510, verbose_name="Title"),
        ),
    ]
