# Generated by Django 4.2.23 on 2025-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_project_settings_alter_project_status_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invites',
            field=models.JSONField(blank=True, default=dict, verbose_name='Invites'),
        ),
    ]
