# Generated by Django 4.2.23 on 2025-06-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_collection_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_project_status_valid',
        ),
        migrations.AddField(
            model_name='project',
            name='invitations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Invitations'),
        ),
        migrations.AddField(
            model_name='project',
            name='libraries',
            field=models.ManyToManyField(to='project.library'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(10, 'Draft'), (20, 'Review'), (30, 'Ready'), (40, 'Positioning'), (50, 'Instruction Bound Copies'), (60, 'Instruction Unbound Copies'), (100, 'Archived')], default=10, verbose_name='Status'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('status__in', [10, 20, 30, 40, 50, 60, 100])), name='project_project_status_valid'),
        ),
    ]
