# Generated by Django 4.2.23 on 2025-06-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_project_invites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='invites',
            new_name='invitations',
        ),
    ]
