# Generated by Django 4.2.23 on 2025-06-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_project_project_project_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='alias',
            field=models.CharField(blank=True, help_text='Alias for a duplicate collection in the same library', max_length=255, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='collection',
            name='exclusion_reason',
            field=models.CharField(blank=True, help_text='Reason for excluding the collection from deduplication', max_length=255, verbose_name='Exclusion reason'),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_excluded',
            field=models.BooleanField(default=False, help_text='Indicates if the collection is excluded from the deduplication process', verbose_name='Is excluded'),
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.IntegerField(help_text='Positioning rank of a collection', null=True, verbose_name='Rank'),
        ),
        migrations.AddField(
            model_name='collection',
            name='positioning_comment',
            field=models.TextField(blank=True, help_text="Instructor's comment on the collection positioning", verbose_name='Positioning comment'),
        ),
    ]
