# Generated by Django 4.2.23 on 2025-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_rename_invites_project_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='libraries',
            field=models.ManyToManyField(to='project.library'),
        ),
        migrations.AlterField(
            model_name='project',
            name='invitations',
            field=models.JSONField(blank=True, default=dict, verbose_name='Invitations'),
        ),
    ]
