# Generated by Django 4.2.23 on 2025-07-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0010_remove_project_project_project_status_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="library",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="project.library",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="invitations",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Invitations"
            ),
        ),
    ]
