# Generated by Django 4.2.23 on 2025-07-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_actionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='is_alternate_site',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE project_project_libraries RENAME TO project_projectlibrary",
                    reverse_sql="ALTER TABLE project_projectlibrary RENAME TO project_project_libraries",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ProjectLibrary',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_alternative_storage_site', models.BooleanField(default=False, verbose_name='Is alternative storage site')),
                        ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.library')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                    ],
                ),
                migrations.AlterField(
                    model_name='project',
                    name='libraries',
                    field=models.ManyToManyField(through='project.ProjectLibrary', to='project.library'),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ProjectLibrary",
            name="is_alternative_storage_site",
            field=models.BooleanField(default=False, verbose_name='Is alternative storage site')
        ),
        migrations.AddConstraint(
            model_name='projectlibrary',
            constraint=models.UniqueConstraint(fields=('project', 'library'), name='unique_project_library'),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE project_projectlibrary DROP CONSTRAINT project_project_libraries_project_id_library_id_a7bb8a4e_uniq",
            reverse_sql="ALTER TABLE project_projectlibrary ADD CONSTRAINT project_project_libraries_project_id_library_id_a7bb8a4e_uniq UNIQUE (project_id, library_id)",
        )
    ]
