# Generated by Django 4.2.23 on 2025-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0013_remove_library_is_alternate_site_projectlibrary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
