# Generated by Django 4.2.23 on 2025-07-21 14:34

from django.db import migrations


def migrate_data_forwards(apps, schema_editor):
    Collection = apps.get_model("project", "Collection")
    Resource = apps.get_model("project", "Resource")

    for collection in Collection.objects.filter(resource__isnull=True):
        resource, _created = Resource.objects.get_or_create(
            code=collection.code,
            title=collection.title,
            project=collection.project,
        )
        collection.resource = resource
        collection.save(update_fields=["resource"])


def migrate_data_backwards(apps, schema_editor):
    Collection = apps.get_model("project", "Collection")
    Resource = apps.get_model("project", "Resource")

    # Remove resource from collections and set code and project from resource
    for collection in Collection.objects.all():
        resource = Resource.objects.get(id=collection.resource_id)
        collection.title = resource.title
        collection.code = resource.code
        collection.project = resource.project
        collection.save(update_fields=["title", "code", "project"])


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0015_collection_is_result_collection_alter_project_name_and_more"),
    ]

    operations = [migrations.RunPython(code=migrate_data_forwards, reverse_code=migrate_data_backwards)]
