# Generated by Django 4.2.23 on 2025-07-21 14:48

import django.db.models.deletion
from django.db import migrations, models


def add_code_field(apps, schema_editor):
    Collection = apps.get_model("project", "Collection")
    # Ajoute la colonne avec une valeur par défaut
    code_field = models.CharField(max_length=25, default="", name="code")
    code_field.set_attributes_from_name("code")
    schema_editor.add_field(Collection, code_field)
    title_field = models.CharField(max_length=510, default="title", name="title")
    title_field.set_attributes_from_name("title")
    schema_editor.add_field(Collection, title_field)


def remove_collection_fields(apps, schema_editor):
    Collection = apps.get_model("project", "Collection")
    code_field = models.CharField(max_length=25, name="code")
    code_field.set_attributes_from_name("code")
    schema_editor.remove_field(Collection, code_field)
    title_field = models.CharField(max_length=510, name="title")
    title_field.set_attributes_from_name("title")
    schema_editor.remove_field(Collection, title_field)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0016_migrate_collection_to_resource"),
    ]

    operations = [
        migrations.RunPython(code=remove_collection_fields, reverse_code=add_code_field),
        migrations.AlterField(
            model_name="collection",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="project.resource",
            ),
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "ordering": ["resource__title"],
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
    ]
