# Generated by Django 4.2.23 on 2025-08-27 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0018_create_comment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_type', models.CharField(choices=[('bound', 'Bound'), ('unbound', 'Unbound')], default='bound', verbose_name='Segment type')),
                ('content', models.TextField(verbose_name='Segment')),
                ('improvable_elements', models.TextField(blank=True, verbose_name='Improbable elements')),
                ('exception', models.TextField(blank=True, verbose_name='Exception')),
                ('order', models.PositiveSmallIntegerField()),
                ('retained', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='project.collection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('improved_segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improving_segments', to='project.segment'))
            ],
            options={
                'verbose_name': 'Collection segment',
                'verbose_name_plural': 'Collection segments',
            },
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('collection', 'order'), name='unique_collection_order'),
        ),

        migrations.AlterField(
            model_name='collection',
            name='position',
            field=models.IntegerField(blank=True, choices=[(1, 'Position 1'), (2, 'Position 2'), (3, 'Position 3'), (4, 'Position 4'), (0, 'Position excluded')], help_text='Positioning rank of a collection', null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='arbitration',
            field=models.IntegerField(choices=[(0, 'Arbitration Type 0'), (1, 'Arbitration Type 1'), (2, 'No arbitration')], db_index=True, default=2, verbose_name='Arbitration'),
        ),
        migrations.RemoveConstraint(
            model_name='userrole',
            name='unique_user_role_project',
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'instructor'), _negated=True), fields=('user', 'role', 'project'), name='unique_user_role_project'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'instructor')), fields=('user', 'project', 'library'), name='unique_user_project_library_for_instructor'),
        ),
    ]
