# Generated by Django 4.2.23 on 2025-09-02 09:01

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_segment_remove_userrole_unique_user_role_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='segment',
            name='unique_collection_order',
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('collection', 'order'), name='unique_collection_order'),
        ),
    ]
