# Generated by Django 4.2.24 on 2025-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0020_remove_segment_unique_collection_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="status",
            field=models.IntegerField(
                choices=[
                    (10, "Positioning"),
                    (20, "Instruction Bound Copies"),
                    (30, "Control Bound Copies"),
                    (40, "Instruction Unbound Copies"),
                    (50, "Control Unbound Copies"),
                    (60, "Edition"),
                ],
                default=10,
                verbose_name="Status",
            ),
        ),
    ]
