# Generated by Django 4.2.24 on 2025-09-26 14:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0021_remove_collection_code_remove_collection_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pub_period_passed", "Publication Period Passed"),
                            ("discontinuous_segment", "Discontinuous Segment"),
                            (
                                "excp_improvable",
                                "Exception or improvable (off-segment)",
                            ),
                            ("chronological_error", "Chronological Error"),
                            ("segment_overlap", "Overlap Segment"),
                            (
                                "misuse_of_remediated_library",
                                "Improper use of remediated library",
                            ),
                            ("confusing_wording", "Confusing wording"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("fixed", models.BooleanField(default=False)),
                ("fixed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fixed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="project.resource",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="project.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly",
                "verbose_name_plural": "Anomalies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["fixed"], name="project_ano_fixed_2578a8_idx"),
                    models.Index(fields=["type"], name="project_ano_type_7cb8f2_idx"),
                ],
            },
        ),
    ]
