# Generated by Django 4.2.25 on 2025-10-16 08:58

from django.db import migrations, models

import epl.validators


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0023_anomaly_resource_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="issn",
            field=models.CharField(
                blank=True,
                max_length=9,
                validators=[epl.validators.IssnValidator()],
                verbose_name="ISSN",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="numbering",
            field=models.CharField(blank=True, verbose_name="Numbering"),
        ),
        migrations.AddField(
            model_name="resource",
            name="publication_history",
            field=models.CharField(blank=True, verbose_name="Publication history"),
        ),
    ]
