# Generated by Django 4.2.25 on 2025-10-16 09:00

from django.db import migrations


def copy_from_collection_to_resource(apps, schema_editor):
    Collection = apps.get_model("project", "Collection")  # NOSONAR

    for collection in Collection.objects.order_by("resource_id", "id").distinct(
        "resource_id"
    ):  # Getting one collection per resource is sufficient
        if resource := collection.resource:
            resource.issn = collection.issn
            resource.publication_history = collection.publication_history
            resource.numbering = collection.numbering
            resource.save()


def copy_from_resource_to_collection(apps, schema_editor):
    Resource = apps.get_model("project", "Resource")  # NOSONAR

    for resource in Resource.objects.all():
        resource.collections.update(
            issn=resource.issn, publication_history=resource.publication_history, numbering=resource.numbering
        )


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0024_issn_pub_history_and_numbering_fields_on_resource"),
    ]

    operations = [
        migrations.RunPython(
            code=copy_from_collection_to_resource,
            reverse_code=copy_from_resource_to_collection,
        ),
    ]
