# Generated by Django 4.2.25 on 2025-10-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0025_copy_field_content_from_collection_to_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="issn",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="numbering",
        ),
        migrations.RemoveField(
            model_name="collection",
            name="publication_history",
        ),
    ]
