# Generated by Django 4.2.25 on 2025-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0026_remove_issn_pub_history_and_numbering_fields_on_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="validations",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Validations"
            ),
        ),
    ]
