# Generated by Django 4.2.26 on 2025-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_resource_validations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.IntegerField(choices=[(10, 'Positioning'), (15, 'Excluded'), (20, 'Instruction Bound Copies'), (25, 'Anomaly Bound Copies'), (30, 'Control Bound Copies'), (40, 'Instruction Unbound Copies'), (45, 'Anomaly Unbound Copies'), (50, 'Control Unbound Copies'), (60, 'Edition')], default=10, verbose_name='Status'),
        ),
    ]
