# Generated by Django 5.2.11 on 2026-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0028_alter_resource_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="title",
            field=models.CharField(
                db_index=True, max_length=2048, verbose_name="Title"
            ),
        ),
    ]
