# Generated by Django 4.2.20 on 2025-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consortium",
            name="settings",
            field=models.JSONField(default=dict, verbose_name="Tenant settings"),
        ),
        migrations.AddField(
            model_name="domain",
            name="front_domain",
            field=models.CharField(
                blank=True, max_length=253, verbose_name="Frontend domain"
            ),
        ),
        migrations.AlterField(
            model_name="consortium",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="consortium",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Tenant name"),
        ),
    ]
