# Generated by Django 4.2.20 on 2025-04-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_consortium_settings_domain_front_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consortium',
            old_name='settings',
            new_name='tenant_settings',
        ),
    ]
