# Generated by Django 4.2.20 on 2025-04-22 10:18

from django.db import migrations
import epl.apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", epl.apps.user.models.CustomUserManager()),
            ],
        ),
    ]
