# Generated by Django 4.2.20 on 2025-05-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
