# Generated by Django 4.2.20 on 2025-05-09 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('tenant_super_user', 'Tenant Super User'), ('project_creator', 'Project Creator'), ('project_manager', 'Project Manager'), ('instructor', 'Instructor'), ('controller', 'Controller'), ('guest', 'Guest')], max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project User Role',
                'verbose_name_plural': 'Project User Roles',
                'unique_together': {('user', 'project', 'role')},
            },
        ),
    ]
