# Generated by Django 4.2.20 on 2025-05-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="settings",
            field=models.JSONField(default=dict),
        ),
    ]
